Bahmni/form-controls

package.json, src/components/Container.jsx, src/components/Section.jsx, src/components/designer/Section.jsx, src/helpers/ControlRecordTreeBuilder.js, src/helpers/ControlRecordTreeMgr.js, src/helpers/ControlUtil.js, src/helpers/Obs.js, src/helpers/formNamespace.js, src/mapper/ObsGroupMapper.js, src/mapper/ObsListMapper.js, src/mapper/ObsMapper.js, src/mapper/SectionMapper.js, test/components/Container.spec.js, test/components/designer/Section.spec.js, test/helpers/ControlRecord.spec.js, test/helpers/ControlRecordTreeBuilder.spec.js, test/helpers/ControlRecordTreeMgr.spec.js, test/helpers/Obs.spec.js, test/helpers/ObservationMapper.spec.js, test/mapper/ObsGroupMapper.spec.js, test/mapper/ObsListMapper.spec.js, test/mapper/ObsMapper.spec.js, test/mapper/SectionMapper.spec.js
1) Add-more property added for section.
2) This package should be published first and use it in implementer-interface.
3) Find PR for implementer-interface at https://github.com/Bahmni/implementer-interface/pull/4
4) JIRA: https://bahmni.atlassian.net/browse/BAH-740
=> Add More Ability For a Section within a Form

package.json, src/components/Comment.jsx, src/components/ObsControl.jsx, src/components/Row.jsx, src/components/Table.jsx, src/components/designer/Cell.jsx, src/components/designer/Grid.jsx, src/components/designer/ObsControlDesigner.jsx, src/components/designer/Row.jsx, src/components/designer/TableDesigner.jsx, src/constants.js, src/helpers/MapperStore.js, src/helpers/controlsParser.js, src/index.jsx, src/mapper/TableMapper.js, styles/bahmniAppsFormBuilder/_form.scss, styles/common/_grid.scss, test/components/Row.spec.js, test/components/Table.spec.js, test/components/designer/Cell.spec.js, test/components/designer/TableDesigner.spec.js, test/helpers/ControlUtil.spec.js, test/helpers/MapperStore.spec.js, test/mapper/TableMapper.spec.js
1. Table control for form-builder
2. This package should be published first and use it in implementer-interface and bahmniapps.
3. JIRA: https://bahmni.atlassian.net/browse/BAH-748
=> [Form Builder] Create and render a table inside form

package.json, src/helpers/formRenderer.js
Add method to fetch record tree of form builder forms
JIRA link: https://bahmni.atlassian.net/browse/BAH-766
=> #BAH-766 | FormsV2 View & Edit for display control

styles/common/_grid.scss
JIRA - https://bahmni.atlassian.net/browse/BAH-886
=> BAH-886  | Format not aligned for Coded answers

package.json, src/helpers/ControlRecordWrapper.js, test/helpers/ControlRecordWrapper.spec.js
[BAH-968](https://bahmni.atlassian.net/browse/BAH-968)
=> BAH-968 | Sowmika | Create hideAndClear method to clear obs when hidden

src/components/Container.jsx, src/helpers/ExecuteEvents.js, src/helpers/FormContext.js, src/helpers/ScriptRunner.js, src/helpers/scriptRunner.js, src/mapper/CodedValueMapper.js, test/components/Container.spec.js, test/helpers/ExecuteEvents.spec.js, test/helpers/FormContext.spec.js
Form conditions support for section add-more(newly added sections)
https://bahmni.atlassian.net/browse/BAH-991
=> BAH-991 | Form conditions section addmore

src/components/Button.jsx, src/components/Comment.jsx, src/components/ObsControl.jsx, src/components/ObsGroupControl.jsx, src/components/designer/Button.jsx, src/components/designer/Comment.jsx, src/components/designer/ObsControlDesigner.jsx, src/components/designer/ObsGroupControlDesigner.jsx, src/helpers/Concept.js, styles/bahmniAppsFormBuilder/_form.scss, styles/common/_autoComplete.scss, styles/common/_grid.scss, test/components/ObsControl.spec.js, test/components/ObsGroupControl.spec.js, test/components/designer/ObsControlDesigner.spec.js, test/components/designer/ObsGroupControlDesigner.spec.js, test/intlEnzymeTest.js
[BAH-1005](https://bahmni.atlassian.net/browse/BAH-1005)
=> BAH-1005 | Ui fixes

src/helpers/formRenderer.js, src/helpers/scriptRunner.js, test/helpers/formRenderer.spec.js
Jira link: https://bahmni.atlassian.net/browse/BAH-1009
Bahmniapps has dependency on this pr.
So, this pr has to be merged before, this one https://github.com/Bahmni/openmrs-module-bahmniapps/pull/283
=> BAH-1009 | Alekhya | Execute the onFormSave event when form save is clicked in consultation

src/components/Comment.jsx, src/components/ObsControl.jsx, src/components/designer/Comment.jsx, src/components/designer/Label.jsx, src/components/designer/ObsControlDesigner.jsx, styles/bahmniAppsFormBuilder/_form.scss, test/components/designer/ObsControlDesigner.spec.js
[BAH - 1016](https://bahmni.atlassian.net/browse/BAH-1016)
=> BAH - 1016 | Ui enhancements pr

package.json, src/helpers/formRenderer.js, test/helpers/formRenderer.spec.js
https://bahmni.atlassian.net/browse/BAH-1017
=> BAH-1017 | Preview and onSave event error handling 

src/helpers/ValueMapperStore.js, src/index.jsx, src/mapper/CodedMultiSelectValueMapper.js, test/helpers/ValueMapperStore.spec.js, test/mapper/CodedMultiSelectValueMapper.spec.js
[BAH-1032](https://bahmni.atlassian.net/browse/BAH-1032)
=> Sowmika | BAH-1032 | Add getValue api for coded multiSelect

src/components/Container.jsx
* Bindu, Tarun | MOBN-1551 | added callback method to get the container data object
* Bindu, Tarun | MOBN-1551 | Refactor code and fix unit tests
Co-authored-by: tarunkumar-tw <tarunkumar.s@thoughtworks.com>
https://bahmni.atlassian.net/browse/BAH-1017
=> Bindu, Tarun | BAH-1017 | MOBN-1551  | Save event not working in Preview Tab

src/components/Container.jsx, test/components/Container.spec.js
* Tarun,Supriya | MOBN-1188 | Fix issues with complex concepts when addMore is enabled
* Supriya, Tarun | MOBN-1188 | Fix unit tests
* Supriya, Tarun | MOBN-1188 | Fix issues for complex concepts with addMore enabled
* Supriya, Tarun | MOBN-1188 | Fix issues for complex concepts with addMore enabled
* Supriya, Tarun | MOBN-1188 | Add unit tests for canAddNextFormFieldPath
Co-authored-by: Supriya Muppiri <supriya.muppiri@thoughtworks.com>
https://bahmni.atlassian.net/browse/BAH-1132
=> Supriya, Tarun | BAH-1132 | MOBN-1188 | Fix issues with complex concepts when addMore is enabled

src/helpers/Validator.js, test/helpers/Validator.spec.js
JIRA : [https://bahmni.atlassian.net/browse/BAH-2297](https://bahmni.atlassian.net/browse/BAH-2297)
Form :
=> BAH-2297 | Siva Reddy | fix for range validation

package.json
=> Siva | Bump up version to 0.93.7

src/components/AutoComplete.jsx
This PR is about 
- Adding reverse order words and partial search for form-2 forms
=> BAH-2421 - [ Rohit ] - Adds reverse order words and partial search for form-2 forms

src/components/AutoComplete.jsx, test/components/AutoComplete.spec.js
This PR is about
- Fixing test and lint issue to resolve to resolve build issue
=> BAH-2421 - [ Rohit ] - Fixes test and lint issue to resolve to resolve build issue

src/components/AutoComplete.jsx, src/components/CodedControl.jsx, src/components/ObsControl.jsx, src/components/designer/CodedControl.jsx, src/helpers/Util.js, test/components/AutoComplete.spec.js, test/components/CodedControl.spec.js, test/components/designer/CodedControl.spec.js, test/helpers/Util.spec.js
Jira - https://bahmni.atlassian.net/browse/BS-33
Configure dropdown/autocomplete on a form with OpenMRS Concepts as questions and SNOMED as answers In the form builder screen
=> BS-33 - Configure form builder to use SNOMED - dropdown / autocomplete

src/components/AutoComplete.jsx, src/components/CodedControl.jsx, src/helpers/Util.js, test/components/AutoComplete.spec.js, test/components/CodedControl.spec.js, test/helpers/Util.spec.js
Add debounce to autocomplete input
https://bahmni.atlassian.net/browse/BS-33
=> BS-33 | Patrick | Add debounce to autocomplete

README.md
Add wiki  Link to the readme
Jira
https://bahmni.atlassian.net/browse/BS-113
=> Add wiki  Link to readme

.github/workflows/npm-publish.yml
JIRA - https://bahmni.atlassian.net/browse/BAH-3048
=> BAH-3048 | Narendra | Added logic to publish only on tag pushed and skip when committed

package.json
JIRA => https://bahmni.atlassian.net/browse/BS-91
=> Bump up version to 0.93.12 - snomed milestone 1 changes

src/components/Label.jsx, styles/bahmniAppsFormBuilder/_form.scss
https://bahmni.atlassian.net/browse/BAH-3142
=> BAH-3142 | Make text inside disabled fields more readable

src/components/Label.jsx, styles/bahmniAppsFormBuilder/_form.scss
Reverts Bahmni/form-controls#94
=> Revert "BAH-3142 | Make text inside disabled fields more readable"

styles/bahmniAppsFormBuilder/_form.scss
https://bahmni.atlassian.net/browse/BAH-3142
=> Make disabled field text more visible

package.json, src/components/AutoComplete.jsx, src/components/Image.jsx, src/components/designer/ComplexControlDesigner.jsx
Asana - https://app.asana.com/0/1204322126657135/1205091497255884
This PR has changes to fix to support Provider and Location complex types to have mandatory control properties as well as to add mandatory image
=> Product Bug | Forms2Forms complex and image type does not have mandatory control properties type concepts

src/components/AutoComplete.jsx, src/components/Provider.jsx
- fixes selected value not coming up for the complex data handler for provider
Bug ref : https://app.asana.com/0/1204322126657135/1205474115440290/f
=> [Bug] Kavitha | A-1205474115440290 | Fix provider dropdown

src/helpers/ControlRecordWrapper.js
Asana Link: https://app.asana.com/0/1204322126657135/1205559175340252/f
=> Add interpretation to handle abnormal button

.github/workflows/npm-publish.yml, .github/workflows/validate-pr.yml, package-lock.json, package.json, src/components/AutoComplete.jsx, src/components/Image.jsx, src/components/Provider.jsx, src/components/designer/ComplexControlDesigner.jsx, src/helpers/ControlRecordWrapper.js
JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?selectedIssue=BAH-3271
This PR has changes to 
- bring in mandatory options for complex control and image fields in forms.
- add loader to wait for the provider API response to get resolved.
=> BAH-3271 | Ability to set mandatory fields for complex controls and images

package-lock.json, package.json, src/components/AutoComplete.jsx, test/components/AutoComplete.spec.js, yarn.lock
JIRA link - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?selectedIssue=BAH-3700
=> BAH-3700 | Autocomplete Dropdown field with Multiselect acting flaky after selecting a value

package-lock.json, package.json, styles/bahmniAppsFormBuilder/_form.scss
=> BAH-3142 | To address issues related to CSS changes in Forms

.github/workflows/npm-publish.yml, .github/workflows/validate-pr.yml
This PR aims to resolve the Node version and GHA Runner Incompatibility by explicitly defining the architecture to 'x64'.
=> [Rahul] | Fix. Node - Runner Incompatibility
